<?php

namespace Proxies\__CG__\Entities\intranet;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Droit extends \Entities\intranet\Droit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIddroit()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["iddroit"];
        }
        $this->__load();
        return parent::getIddroit();
    }

    public function setModification($modification)
    {
        $this->__load();
        return parent::setModification($modification);
    }

    public function getModification()
    {
        $this->__load();
        return parent::getModification();
    }

    public function setLecture($lecture)
    {
        $this->__load();
        return parent::setLecture($lecture);
    }

    public function getLecture()
    {
        $this->__load();
        return parent::getLecture();
    }

    public function setIdmodule(\Entities\intranet\Module $idmodule = NULL)
    {
        $this->__load();
        return parent::setIdmodule($idmodule);
    }

    public function getIdmodule()
    {
        $this->__load();
        return parent::getIdmodule();
    }

    public function setIdutilisateur(\Entities\intranet\Utilisateur $idutilisateur = NULL)
    {
        $this->__load();
        return parent::setIdutilisateur($idutilisateur);
    }

    public function getIdutilisateur()
    {
        $this->__load();
        return parent::getIdutilisateur();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'iddroit', 'modification', 'lecture', 'idmodule', 'idutilisateur');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}