<?php

namespace Proxies\__CG__\Entities\intranet;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Utilisateur extends \Entities\intranet\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdutilisateur()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idutilisateur"];
        }
        $this->__load();
        return parent::getIdutilisateur();
    }

    public function setIdUserStaff($idUserStaff)
    {
        $this->__load();
        return parent::setIdUserStaff($idUserStaff);
    }

    public function getIdUserStaff()
    {
        $this->__load();
        return parent::getIdUserStaff();
    }

    public function setLoginutilisateur($loginutilisateur)
    {
        $this->__load();
        return parent::setLoginutilisateur($loginutilisateur);
    }

    public function getLoginutilisateur()
    {
        $this->__load();
        return parent::getLoginutilisateur();
    }

    public function setPasswordutilisateur($passwordutilisateur)
    {
        $this->__load();
        return parent::setPasswordutilisateur($passwordutilisateur);
    }

    public function getPasswordutilisateur()
    {
        $this->__load();
        return parent::getPasswordutilisateur();
    }

    public function setNomutilisateur($nomutilisateur)
    {
        $this->__load();
        return parent::setNomutilisateur($nomutilisateur);
    }

    public function getNomutilisateur()
    {
        $this->__load();
        return parent::getNomutilisateur();
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }

    public function setFonction($fonction)
    {
        $this->__load();
        return parent::setFonction($fonction);
    }

    public function getFonction()
    {
        $this->__load();
        return parent::getFonction();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setValideur($valideur)
    {
        $this->__load();
        return parent::setValideur($valideur);
    }

    public function getValideur()
    {
        $this->__load();
        return parent::getValideur();
    }

    public function setLineIdentifier($lineIdentifier)
    {
        $this->__load();
        return parent::setLineIdentifier($lineIdentifier);
    }

    public function getLineIdentifier()
    {
        $this->__load();
        return parent::getLineIdentifier();
    }

    public function setLine($line)
    {
        $this->__load();
        return parent::setLine($line);
    }

    public function getLine()
    {
        $this->__load();
        return parent::getLine();
    }

    public function setGestion($gestion)
    {
        $this->__load();
        return parent::setGestion($gestion);
    }

    public function getGestion()
    {
        $this->__load();
        return parent::getGestion();
    }

    public function setProfil($profil)
    {
        $this->__load();
        return parent::setProfil($profil);
    }

    public function getProfil()
    {
        $this->__load();
        return parent::getProfil();
    }

    public function setCodeDepartement(\Entities\intranet\Departement $codeDepartement = NULL)
    {
        $this->__load();
        return parent::setCodeDepartement($codeDepartement);
    }

    public function getCodeDepartement()
    {
        $this->__load();
        return parent::getCodeDepartement();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idutilisateur', 'idUserStaff', 'loginutilisateur', 'passwordutilisateur', 'nomutilisateur', 'prenom', 'fonction', 'email', 'valideur', 'lineIdentifier', 'line', 'gestion', 'profil', 'codeDepartement');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}